export { TopRatedSection } from "./top-rated-section";
export { NowPlayingSection } from "./now-playing-section";
export { UpComingSection } from "./upcoming-section";
export { MainBannerSection } from "./main-banner-section";
export { DetailHeaderSection } from "./detail-header-section";
export { DetailBodySection } from "./detail-body-section";
export { DetailCreditsSection } from "./detail-credits-section";
export { DetailRelatedSection } from "./detail-related-section";
export { DetailTrailerSection } from "./detail-trailer-section";
