export * from "./top-rated-section";
export * from "./now-playing-section";
export * from "./upcoming-section";
export * from "./main-banner-section";
export * from "./detail-header-section";
export * from "./detail-body-section";
export * from "./detail-credits-section";
export * from "./detail-related-section";
export * from "./detail-trailer-section";
